// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA09j3HhOCSuTzeDmbYaB3JksufxH-AZd4',
    appId: '1:950307853854:web:a896f3d5e151f2feec400f',
    messagingSenderId: '950307853854',
    projectId: 'chat-app-91f0b',
    authDomain: 'chat-app-91f0b.firebaseapp.com',
    storageBucket: 'chat-app-91f0b.appspot.com',
    measurementId: 'G-5VDHNLC1T9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpVnSl5RZw660sPuyllOj-whSTBWonOZc',
    appId: '1:950307853854:android:2f5a0557720448ceec400f',
    messagingSenderId: '950307853854',
    projectId: 'chat-app-91f0b',
    storageBucket: 'chat-app-91f0b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjI1Ro25sjiZzhp2pLYzpYWYUAy9ISDBQ',
    appId: '1:950307853854:ios:a6f68a3375f0332dec400f',
    messagingSenderId: '950307853854',
    projectId: 'chat-app-91f0b',
    storageBucket: 'chat-app-91f0b.appspot.com',
    iosClientId: '950307853854-1h5tp55v3u7ql77l095gpth3nj3qndb4.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatScholarApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjI1Ro25sjiZzhp2pLYzpYWYUAy9ISDBQ',
    appId: '1:950307853854:ios:a6f68a3375f0332dec400f',
    messagingSenderId: '950307853854',
    projectId: 'chat-app-91f0b',
    storageBucket: 'chat-app-91f0b.appspot.com',
    iosClientId: '950307853854-1h5tp55v3u7ql77l095gpth3nj3qndb4.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatScholarApp',
  );
}
